#!/usr/bin/env bash
# Copyright (c) 2026 AO Cyber Systems
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# SPDX-License-Identifier: MIT

# build-ios.sh builds the DART-01 cgo shim (bind/capi) into a device c-archive
# and a lipo'd-universal simulator c-archive, then packages both into one
# EdenPress.xcframework -- DART-02's native iOS recipe. Static linking
# (c-archive), NOT c-shared: this is the exact static-library shape 07-05's
# `plugin_ffi` iOS podspec consumes via `vendored_libraries` (RESEARCH §2/§4).
# NO `gomobile bind` anywhere -- plain `go build -buildmode=c-archive`.
#
# GOTCHA (RESEARCH §2/§4): device arm64 and simulator arm64 share the SAME
# GOARCH/arch name, so they can NEVER be lipo'd together into one .a -- the
# .xcframework container is what keeps them apart while still shipping "one"
# artifact to consumers.
#
# GOTCHA (carry to 07-05 docs): Xcode strips symbols on release builds by
# default (Build Settings -> Strip Style: "All Symbols"), which breaks
# `DynamicLibrary.process()` symbol lookups at runtime with no build-time
# warning. The consuming app must set Strip Style -> "Non-Global Symbols".
#
# This script requires macOS + a full Xcode install (not just Command Line
# Tools) -- iOS c-archive slices cannot be cross-compiled from Linux. It is
# expected to run successfully on this dev host; CI additionally verifies it
# on a pinned macos runner (.github/workflows/dart-native.yml).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

if [ "$(uname -s)" != "Darwin" ]; then
	echo "FAIL: build-ios.sh requires macOS + Xcode (iOS c-archive slices" >&2
	echo "cannot be cross-compiled from Linux)." >&2
	exit 1
fi

if ! XCODE_PATH="$(xcode-select -p 2>/dev/null)"; then
	echo "FAIL: 'xcode-select -p' failed. Install Xcode, then run:" >&2
	echo "  sudo xcode-select -s /Applications/Xcode.app/Contents/Developer" >&2
	exit 1
fi
case "$XCODE_PATH" in
*/Xcode.app/*) ;;
*)
	echo "FAIL: xcode-select points at '$XCODE_PATH' -- this looks like" >&2
	echo "Command Line Tools only, not a full Xcode install. Run:" >&2
	echo "  sudo xcode-select -s /Applications/Xcode.app/Contents/Developer" >&2
	exit 1
	;;
esac

# Sanity-check the Go toolchain's own iOS support is present -- if this is
# missing, GOROOT/Go-version is misconfigured regardless of Xcode.
GO_IOS_CLANGWRAP="$(go env GOROOT)/misc/ios/clangwrap.sh"
if [ ! -f "$GO_IOS_CLANGWRAP" ]; then
	echo "FAIL: expected Go iOS support file not found: $GO_IOS_CLANGWRAP" >&2
	echo "This ships with the Go toolchain (misc/ios/clangwrap.sh); confirm" >&2
	echo "GOROOT ($(go env GOROOT)) and the installed Go version." >&2
	exit 1
fi

# Pinned iOS deployment target (RESEARCH Open Question 3: no project min-OS was
# committed elsewhere, so this is the chosen, recorded value -- bump alongside
# 07-05's actual Flutter min-iOS support, not silently).
IOS_MIN_VERSION="13.0"

BUILD_ROOT="bind/capi/build/ios"
rm -rf "$BUILD_ROOT"
mkdir -p "$BUILD_ROOT"
# go build's CC must be an absolute path (a relative CC is rejected outright),
# so resolve BUILD_ROOT to an absolute path before generating wrapper scripts.
BUILD_ROOT="$(cd "$BUILD_ROOT" && pwd)"

# make_wrapper SDK MIN-VERSION-FLAG ARCH OUT-PATH
#
# Adapted from $(go env GOROOT)/misc/ios/clangwrap.sh, whose own header
# comment says: "If you'd like to build for real iOS devices, change SDK to
# iphoneos and PLATFORM to ios." We generate device AND simulator wrapper
# variants ourselves (rather than relying on the stock wrapper's hardcoded
# simulator-only default) so ONE pinned IOS_MIN_VERSION applies consistently
# to every slice.
make_wrapper() {
	sdk="$1"
	minflag="$2"
	arch="$3"
	out="$4"
	cat >"$out" <<WRAPEOF
#!/bin/sh
# Generated by scripts/build-ios.sh -- do not edit, do not commit.
SDK_PATH=\$(xcrun --sdk $sdk --show-sdk-path)
CLANG=\$(xcrun --sdk $sdk --find clang)
exec "\$CLANG" -arch $arch -isysroot "\$SDK_PATH" -m${minflag}=$IOS_MIN_VERSION "\$@"
WRAPEOF
	chmod +x "$out"
}

make_wrapper iphoneos iphoneos-version-min arm64 "$BUILD_ROOT/device-clangwrap.sh"
make_wrapper iphonesimulator ios-simulator-version-min arm64 "$BUILD_ROOT/sim-arm64-clangwrap.sh"
make_wrapper iphonesimulator ios-simulator-version-min x86_64 "$BUILD_ROOT/sim-x86_64-clangwrap.sh"

# build_slice NAME GOARCH WRAPPER
#
# NOTE: device-arm64 and sim-arm64 share GOARCH=arm64 -- `-a` forces a full
# rebuild so Go's build cache never conflates the two (different CC/isysroot,
# same GOOS/GOARCH tuple).
build_slice() {
	name="$1"
	goarch="$2"
	wrapper="$3"
	out_dir="$BUILD_ROOT/$name"
	mkdir -p "$out_dir"
	echo "build-ios: $name (GOOS=ios GOARCH=$goarch) via $(basename "$wrapper")"
	CGO_ENABLED=1 GOOS=ios GOARCH="$goarch" CC="$wrapper" \
		go build -a -buildmode=c-archive -tags ios -o "$out_dir/libpress.a" ./bind/capi

	test -f "$out_dir/libpress.a" || {
		echo "FAIL: $out_dir/libpress.a not produced" >&2
		exit 1
	}
	test -f "$out_dir/libpress.h" || {
		echo "FAIL: $out_dir/libpress.h not produced" >&2
		exit 1
	}
	echo "  $(lipo -info "$out_dir/libpress.a")"
}

# CRITICAL: plain `go build -buildmode=c-archive` per arch. NO gomobile bind.
build_slice device-arm64 arm64 "$BUILD_ROOT/device-clangwrap.sh"
build_slice sim-arm64 arm64 "$BUILD_ROOT/sim-arm64-clangwrap.sh"
build_slice sim-x86_64 amd64 "$BUILD_ROOT/sim-x86_64-clangwrap.sh"

# Merge the two SIMULATOR slices into one universal .a via lipo. The device
# slice is kept separate (see GOTCHA above: device+sim arm64 cannot be merged).
SIM_UNIVERSAL_DIR="$BUILD_ROOT/simulator-universal"
mkdir -p "$SIM_UNIVERSAL_DIR"
lipo -create -output "$SIM_UNIVERSAL_DIR/libpress.a" \
	"$BUILD_ROOT/sim-arm64/libpress.a" \
	"$BUILD_ROOT/sim-x86_64/libpress.a"
cp "$BUILD_ROOT/sim-arm64/libpress.h" "$SIM_UNIVERSAL_DIR/libpress.h"
echo "build-ios: simulator-universal (lipo arm64+x86_64)"
echo "  $(lipo -info "$SIM_UNIVERSAL_DIR/libpress.a")"

# Package device + simulator-universal into one .xcframework -- the artifact
# 07-05's plugin_ffi iOS podspec vendors.
XCFRAMEWORK="$BUILD_ROOT/EdenPress.xcframework"
rm -rf "$XCFRAMEWORK"
xcodebuild -create-xcframework \
	-library "$BUILD_ROOT/device-arm64/libpress.a" -headers "$BUILD_ROOT/device-arm64" \
	-library "$SIM_UNIVERSAL_DIR/libpress.a" -headers "$SIM_UNIVERSAL_DIR" \
	-output "$XCFRAMEWORK"

test -d "$XCFRAMEWORK" || {
	echo "FAIL: $XCFRAMEWORK was not created" >&2
	exit 1
}

# Verify the xcframework contains BOTH a device (ios-arm64) slice dir and a
# simulator (ios-*-simulator) slice dir.
if ! find "$XCFRAMEWORK" -maxdepth 1 -type d -name 'ios-arm64' | grep -q .; then
	echo "FAIL: $XCFRAMEWORK is missing its device (ios-arm64) slice directory" >&2
	ls "$XCFRAMEWORK" >&2
	exit 1
fi
if ! find "$XCFRAMEWORK" -maxdepth 1 -type d -name 'ios-*-simulator' | grep -q .; then
	echo "FAIL: $XCFRAMEWORK is missing its simulator (ios-*-simulator) slice directory" >&2
	ls "$XCFRAMEWORK" >&2
	exit 1
fi

echo "PASS: device-arm64, sim-arm64, sim-x86_64 c-archives built; simulator-universal" \
	"lipo'd; $XCFRAMEWORK contains device + simulator slices. No gomobile used."
